apiVersion: apps/v1
kind: Deployment
metadata:
  name: continuous-integration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: pod
        image: shivabogem/pipeline:1.0-12
        ports:
        - containerPort: 8080
