apiVersion: apps/v1
kind: Deployment
metadata:
  name: continuos-integration
spec:
  replicas: 3
selector:
  matchLabels:
    app: test
  template:
    metadata:
      labels:
        app:test
    spec:
      containers:
      - name: ci
        image: shivabogem/pipeline:1.0-12
        ports:
        - containerPort: 8080
