apiVersion:apps/v1
kind: Deployment
metadata:
  name: continuous-integration
spec:
  replicas: 2
  selector:
    matchlabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: pod
        image: shivabogem/pipeline
        ports:
        - containerPort: 8080
